name: Build and deploy Node.js app to Azure Web App - Bank-Sampah-Bersinar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install and build frontend
        run: |
          cd frontend
          pnpm install
          pnpm run build

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: |
            backend/
            backend/web.config

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend

      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend

      - name: Ensure backend/public directory exists
        run: mkdir -p backend/public

      - name: Copy frontend build to backend
        run: |
          cp -a frontend/dist/. backend/public/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Bank-Sampah-Bersinar"
          slot-name: "Production"
          package: backend/
