name: Build and Deploy Backend to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Build backend
        run: |
          cd backend
          npm run build

      - name: Upload backend artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v2
        with:
          name: backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "bank-sampah-bersinar"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend
