name: Build and deploy Node.js and React app to Azure Web App - Bank-Sampah-Bersinar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install and build backend
        run: |
          cd backend
          pnpm install
          pnpm run build --if-present

      - name: Install dependencies for frontend
        run: |
          cd frontend
          pnpm install

      - name: Verify frontend package.json
        run: |
          cat frontend/package.json

      - name: Build frontend
        run: |
          cd frontend
          pnpm run build
        env:
          CI: false

      - name: Output frontend build logs
        run: |
          cd frontend
          pnpm run build --verbose

      - name: List frontend directory
        run: |
          cd frontend
          ls -al

      - name: List frontend dist directory
        run: |
          cd frontend/dist
          ls -al

      - name: Upload backend artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: backend/

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: frontend/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v2
        with:
          name: backend
          path: backend

      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: frontend

      - name: List downloaded frontend artifact
        run: |
          ls -al frontend

      - name: Copy frontend build to backend
        run: |
          mkdir -p backend/frontend/build
          cp -a frontend/. backend/frontend/build/

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Bank-Sampah-Bersinar"
          slot-name: "Production"
          package: backend
